### ISSUE TITLE
ESS Scaling group not setting loadbalancer_ids

### ISSUE THREAD

**Issue by jlwynkoop** [alibaba/terraform-provider#284] opened 2017-11-21 20:25 UTC
When creating a scaling group as follows:

resource "alicloud_ess_scaling_group" "esg" {
  provider           = "alicloud.${var.alicloud_region}"
  count              = "${var.az_count}"
  vswitch_id         = "${element(var.ess_vswitch_ids, count.index)}"
  min_size           = "${var.ess_scaling_min_size}"
  max_size           = "${var.ess_scaling_max_size}"
  scaling_group_name = "${var.ess_scaling_group_name}-${element(var.ess_vswitch_names, count.index)}"
  removal_policies   = "${var.ess_removal_policies}"
  loadbalancer_ids   = [ "${var.ess_loadbalancer_ids}" ]
}

'terraform plan' reports that the loadbalancer_ids will be set correctly, however after the group is created, aliyuncli reports that no loadbalancer_ids are associated with the group.

**Comment by xiaozhu36** [comment] 2017-11-23 03:58
Hi @jlwynkoop 

I am sorry for that. It is ours provider's bug and I will fix it as soon as possible. Please be patient, thanks a lot.

Regards,
He Guimin

**Comment by philippevidal80** [comment] 2017-11-30 18:52
Hi,

We also tried to do the same thing (link a Scaling Group with SLB) but result in a Scaling Group with no SLB attached (no SLB visible in Scaling Group part of the Web Console).

But we can observe that Terraform state is aware of the SLB id in the Scaling Group resource ... Everything seems OK on TF side.

**Comment by xiaozhu36** [comment] 2017-12-06 09:20
Hi @jlwynkoop at present, Terraform supports association SLB instance with Scaling Group, and you can ensure the associated SLB by Web Console.

@philippevidal80 Web Console also supports  association SLB instance with Scaling Group. It is visible when you create a new Scaling Group.

**Comment by xiaozhu36** [comment] 2017-12-13 02:02
Hi @jlwynkoop  “after the group is created, aliyuncli reports that no loadbalancer_ids are associated with the group“ Could you please provide some aliyuncli error details for the issue?

**Comment by jlwynkoop** [comment] 2017-12-13 03:01
@xiaozhu36 Aliyun CLI does not give me any error.  What happens is that, after executing TF plan, the Loadbalancer ID is not set for the ESG, even though terraform said it created the ESG with the SLB ID.  Here is a gist with the terraform output and the aliyuncli output, line 39 is where i'd expect to see the SLB ID in the ESG, but it's not there...

https://gist.github.com/jlwynkoop/01d9cc1ff1b8e6601777af8c1352659f

**Comment by xiaozhu36** [comment] 2017-12-13 03:13
Hi @jlwynkoop if Web Console also shows no SLB ID associated to the ESG, it is may be terraform associating SLB failed. This may be a bug and I will deal it as soon as possible, thanks a lot.

Regards,
He Guimin

**Comment by jlwynkoop** [comment] 2017-12-13 03:14
Correct, Web Console also shows no SLB ID associated to the ESG

**Comment by xiaozhu36** [comment] 2017-12-13 13:11
Hi @jlwynkoop The issue has been fixed by [version 1.3.2](https://github.com/alibaba/terraform-provider/releases/tag/V1.3.2). Please update and try again, thanks a lot.

Regards
He Guimin

**Comment by jlwynkoop** [comment] 2017-12-13 14:40
Hi @xiaozhu36, the ESG is now created with the LoadBalancerId set, but Terraform gives the following error:
```
* alicloud_ess_scaling_group.esg: Error Describe ESS scaling group Attribute: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:""}, HostId:"", Code:"AliyunGoClientFailure", Message:"json: cannot unmarshal object into Go struct field ScalingGroupItemType.LoadBalancerIds of type string"}, StatusCode:-1}
```

**Closed** 2017-12-14 01:10 UTC

**Comment by 3dw1np** [comment] 2017-12-14 10:14
@philippevidal80 The issue is fixed now.
