### ISSUE TITLE
Always failed when allocating public IP address to ecs

### ISSUE THREAD

**Issue by litian54** [alibaba/terraform-provider#121] opened 2017-05-04 18:36 UTC
Hi there,

I encountered the problem as below, when I was creating a ecs instance in our VPC. However, if I run `terraform apply` again, it will be successful.

This error always happens to me, almost every single time I run `terraform apply`.

Here is the error log,

```
* alicloud_instance.test: allocateIpAndBandWidthRelative err: &errors.errorString{s:"[DEBUG] AllocatePublicIpAddress for instance got error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:\"06FD4F80-B48A-4C02-A213-4486885A2DFD\"}, HostId:
\"ecs-cn-hangzhou.aliyuncs.com\", Code:\"Forbidden.InstanceNotFound\", Message:\"The specified Instance is not found, so we cann't get enough information to check permission in RAM.\"}, StatusCode:404}"}
```

Do you think it is because terraform alicloud provider allocates the public IP address before the ecs instance is created?

Thanks for your help,

Tian

**Comment by xiaozhu36** [comment] 2017-05-05 06:01
Hello @litian54 ,

Thank you for using our product. According to your description, I have made a test and the result is good. Could you please send me your template to help me to locate quickly the problem that you happened ?

Thanks,
Guimin

**Comment by litian54** [comment] 2017-05-05 06:08
Hi Guimin(@xiaozhu36)

Thanks for your responding and help.

Here is my template,
```
resource "alicloud_instance" "my_test" {
  instance_type = "${var.instance_type}"
  image_id = "${var.image_id}"
  count = "${var.instance_count}"
  availability_zone = "${element(split(",", var.availability_zones), count.index)}"
  instance_name = "${var.role}${count.index+1}"
  host_name = "${var.role}${count.index+1}"

  # system disk
  io_optimized = "${var.io_optimized}"
  system_disk_category = "${var.system_disk_category}"
  system_disk_size = "${var.system_disk_size}"

  # networking
  allocate_public_ip = true
  security_groups = ["${split(",", var.security_groups)}"]
  internet_charge_type = "${var.internet_charge_type}"
  internet_max_bandwidth_in = "${var.internet_max_bandwidth_in}"
  internet_max_bandwidth_out = "${var.internet_max_bandwidth_out}"
  vswitch_id = "${var.vswitch_id}"

  instance_charge_type = "PostPaid"

  tags {
    Name = "${var.role}${count.index+1}"
    Owner = "${var.owner}"
    Environment = "${var.environment}"
    Role = "${var.role}"
  }
}
```

And I'm using terraform 0.9.4.

Thank you,

Tian

**Comment by xiaozhu36** [comment] 2017-05-05 06:23
Hello @litian54 

OK, please confirm the following question:

1. What's your availability_zone? Are the instance and your vswitch in the same  region or availability_zone?
2. What's your image_id? And is it available?
3. What's your instance_type? And is it available?

Thanks,
Guimin

**Comment by litian54** [comment] 2017-05-05 17:21
Hi Guimin(@xiaozhu36 )

I'm using,

```
region: cn-beijing
availability_zone: cn-beijing-b
instance type: ecs.e3.xlarge
vpc: China North 2 (Beijing)
```
And `image_id` is our custom image.

We use the template I pasted as a module to launch multiple instances. Actually, it will be successful eventually. But the problem is that we always get the `Forbidden.InstanceNotFound` error at the first `terraform apply`. And then we run `terraform apply` again,  everything goes well.

So we need to run `terraform apply` twice in order to create ecs instances right now.

Thank you,

Tian

**Comment by xiaozhu36** [comment] 2017-05-08 01:46
Hi Tian ( @litian54  )

According to your description, you template can be interpreted as you want to create multiple instances in the cn-beijing-b and you can ensure instances and your vswitch in the same region. However, according to my survey, at present cn-beijing-b doesn't support to create any type instance, so could you please confirm the correct region to help me to find the real reason?  Thank you very much.

Regards,
Guimin

**Comment by xiaozhu36** [comment] 2017-05-08 04:51
Hi Tian ( @litian54 )

I have found the reason, and it is ours fault. I will solve it as soon as possible. Thank you for your contribution.

Regards,
Guimin

**Comment by litian54** [comment] 2017-05-08 17:57
Sounds great! Thanks for your help! @xiaozhu36

**Comment by demonwy** [comment] 2017-05-10 03:31
Hi @litian54 

In the last terraform version, we have fixed the bug when allocate public ip for ecs. 
I wonder your version is more older. Could you upgrade it? Or you can set up alicloud provider separately by https://github.com/alibaba/terraform-provider/releases/tag/V1.0.6 and try again?

Thanks,
YueWang

**Comment by litian54** [comment] 2017-05-10 18:36
Thanks for your help! @demonwy 

I think I'm using the latest version of terraform. For more info,

```
terraform: v0.9.4
region: cn-beijing
availability_zone: cn-beijing-b
instance type: ecs.e3.xlarge
vpc: China North 2 (Beijing)
```

Is this your fix https://github.com/alibaba/terraform-provider/commit/9d197744db87f8b96a4ada996d372c8f9ac0a7f1 ?

I think it is not included in `v0.9.4` of terraform repo. https://github.com/hashicorp/terraform/blob/v0.9.4/builtin/providers/alicloud/resource_alicloud_ess_scalinggroup.go

and not in `v1.0.6` either. https://github.com/alibaba/terraform-provider/blob/V1.0.6/alicloud/resource_alicloud_ess_scalinggroup.go

Thanks for pinpointing the bug is related to "allocate public ip for ecs".

**Comment by demonwy** [comment] 2017-05-10 23:58
The code is located in https://github.com/alibaba/terraform-provider/blob/V1.0.6/alicloud/resource_alicloud_instance.go#L255 of alicloud repo, and in https://github.com/hashicorp/terraform/blob/v0.9.4/builtin/providers/alicloud/resource_alicloud_instance.go#L255 of terraform repo.

And our test case https://github.com/hashicorp/terraform/blob/v0.9.4/builtin/providers/alicloud/resource_alicloud_instance_test.go#L446 is passed all the time.

Could you find the message '[DEBUG] WaitForInstance' in the error log?  It maybe timeout?

Expect more info from you @litian54 ,and thanks for your continuous follow-up.

Regards,
YueWang

**Comment by demonwy** [comment] 2017-05-11 07:31
Hi @litian54 
I have reproduce this issue by a sub account. We will fix it before this weekend.
Thanks again for your report.

**Comment by demonwy** [comment] 2017-06-01 13:02
@litian54  If everything is ok, i will close this issue.

**Closed** 2017-06-01 13:03 UTC
